blank_issues_enabled: false
contact_links:
  - name: Discussão geral
    url: https://github.com/LypexzDev/Projeto-4-frontend-backend/discussions
    about: Use Discussions para ideias e dúvidas abertas.
